easeurl = "https://mijope.de"
languageCode = "en-us"
title = "Michael Johann Peter - IT Consulting"
theme = "hugo-creative-theme"

[markup.goldmark.renderer]
unsafe= true

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Michael Johann Peter"
	description = "Freelancer/IT Consultant in the field of software engineering and IT operations. Topics include cloud environments, containerization, continuous deployments, and build pipelines. Technolgies include AWS, Terraform, Docker, Kubernetes, Jenkins, Ansible, Python, Java, Bash, Debian, CentOS, Git, Jira, Confluence, Grafana, Prometheus"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		  brand = "Michael Johann Peter"
		  [params.navigation.links]
          about     = "About"
          services  = "Services"
          skills    = "Skills"
          portfolio = "Portfolio"
          cv        = "CV"
          contact   = "Contact"


	# Hero section
	[params.hero]
      # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
      slogan     = "„Knowledge is power“"
      subtitle   = "Delivering services in the field of IT operations and software engineering. <br> My goal is to boost your business by enabling your IT!"
      buttonText = "Show me more"


	# About section
	[params.about]
      headline    = "Who am I"
        #description = '''IT is not only my profession but my passion <br> I am a team player <br> I love to develop solutions <br> I have a broad understanding of IT <br> I don't hesitate to learn and improve <br> Experienced remote worker'''
        description = """Passionate <span style="color: #f05f40">automation professional</span> with an emphasis on <span style="color: #f05f40">cloud computing</span> and <span style="color: #f05f40">DevOps</span>. My primary goal is to
<span style="color: #f05f40">enable</span> your business and your developer teams to deliver value. <br>I am familiar with a broad range of IT topics
which allows me to understand and solve problems. <br>Modern IT is highly complex and consists of many layers of
abstraction. My claim is to create <span style="color: #f05f40">simple over complex solutions</span>. No fanciness but easy to understand, use, and
maintain. For me less complexity results in less bugs and more <span style="color: #f05f40">reliability</span>. <br>I am happy to learn new things and also
share them with others because I believe <span style="color: #f05f40">learning and sharing</span> is the key to success in modern IT."""
        buttonText  = "How can I support you?"


	# Service section
	[params.services]
		headline = "My services include"
    buttonText  = "Working with"
        [[params.services.list]]
            icon = "fas fa-code"
            title = "Software Engineering"
            description = "Enable your Engineers to deliver"
        [[params.services.list]]
            icon = "fas fa-server"
            title = "Operations"
            description = "Work with your Devs and Ops"
        [[params.services.list]]
            icon = "fas fa-cloud"
            title = "Cloud Environments"
            description = "Think Cloud Native in AWS"
        [[params.services.list]]
            icon = "fab fa-linux"
            title = "Linux Administration"
            description = "Linux and the shell is my second home"
        [[params.services.list]]
            icon = "fas fa-cogs"
            title = "Automation"
            description = "Automate your boring stuff"
        [[params.services.list]]
            icon = "fa fa-shield-alt"
            title = "IT Security"
            description = "Keep security aspects in mind"
        [[params.services.list]]
            icon = "fas fa-graduation-cap"
            title = "Trainings"
            description = "Enhance productivity and tooling"
        [[params.services.list]]
            icon = "fas fa-pencil-alt"
            title = "Publicity"
            description = "Support you in writing technical articles"


    # Skills section
    [params.skills]
        headline    = "Skills"
        description ="""
<p>
  <span style="color: #f05f40">Working with</span><br>
  Cross functional product teams | infrastructure and platform teams | Kanban | Confluence | Jira<br>
  <span style="color: #f05f40">IT</span><br>
  Networks | advanced Linux knowledge | system architecture | Microservice architecture | cloud native architecture<br>
  <span style="color: #f05f40">Cloud</span><br>
  Terraform | Amazon Web Services | Ansible | Vagrant | Packer<br>
  <span style="color: #f05f40">Kubernetes</span><br>
  Kustomize | Flux | ArgoCD | Kubecost | EKS | KinD | Helm | Kubeval<br>
  <span style="color: #f05f40">DevOps</span><br>
  Java (Spring Boot and Quarkus) | JavaScript(Reactjs, Nextjs, Nodejs) | Python | Elasticsearch<br>
  <span style="color: #f05f40">CI/CD</span><br>
  Gitlab CI/CD | Github Actions | Jenkins | Docker(-swarm)<br>
  <span style="color: #f05f40">Operations</span><br>
  Prometheus | Grafana | Apache2 | Nginx | MariaDB | Postgresql | TomEE | JBoss<br>
  <span style="color: #f05f40">Programming</span><br>
  Python | Bash | Go | K6 Load Testing | Selenium | Vim | Intellij<br>
  <span style="color: #f05f40">IT-Security</span><br>
  Security awareness | Nmap | Burp Suite | Gobuster | Sqlmap | Metasploit<br>
  <span style="color: #f05f40">Other</span><br>
  Git | NextCloud | MS Office | LATEX<br>
  <span style="color: #f05f40">Languages</span><br>
  German (first language) | English<br>
</p>
"""
        buttonText  = "Experience"


    # Portfolio scetion
	  [params.portfolio.modal]
        headline = "Some projects I have been working on"
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"


    # knowledge.rooknecht.net
	  [params.aside]
	  	  headline = "Warning! Technical stuff incoming"
		[params.aside.button]
        text = "My Knowledge Base"
        link = "https://knowledge.rootknecht.net/about"

    # knowledgebase
      [params.knowledgebase]
          headline = "More Details about me"
        [params.knowledgebase.button]
        text = "Curriculum Vitae"
        link = "https://knowledge.rootknecht.net/about"

    # Contact section
    [params.contact]
        headline = "Let's Get In Touch!"
        #description = "Feel free to contact me"
        email = "mailto:me@mijope.de"
        xing = "https://www.xing.com/profile/Michael_Peter94/"
        linkedin = "https://www.linkedin.com/in/michael-peter-4aa918107/"
        github = "https://github.com/Allaman"
        freelancermap = "https://www.freelancermap.de/freelancer-verzeichnis/profile/it-infrastruktur/224527-profil-it-consultant.html"
        vcard = "/vcard.vcf"
